AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 Object Ingestion Catalog - S3 event -> Lambda -> DynamoDB (+ optional API)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref CatalogTable

Parameters:
  ProjectName:
    Type: String
    Default: s3-object-ingestion-catalog

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${AWS::AccountId}-${AWS::Region}-upload"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true  

  CatalogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sourceSystem
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: sourceSystem
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-ingest"
      CodeUri: src/ingest/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${ProjectName}-${AWS::AccountId}-${AWS::Region}-upload/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub "arn:aws:s3:::${ProjectName}-${AWS::AccountId}-${AWS::Region}-upload"

  S3ObjectCreatedRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Route S3 object created events to ingest Lambda
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref UploadBucket
      Targets:
        - Arn: !GetAtt IngestFunction.Arn
          Id: IngestFunctionTarget

  AllowEventBridgeInvokeIngest:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IngestFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt S3ObjectCreatedRule.Arn

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod

  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-query"
      CodeUri: src/query/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CatalogTable
      Environment:
        Variables:
          UPLOAD_BUCKET_NAME: !Sub "${ProjectName}-${AWS::AccountId}-${AWS::Region}-upload"
      Events:
        BySourceSystem:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /sources/{sourceSystem}/objects
            Method: GET
        ByDateRange:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /objects
            Method: GET

Outputs:
  BucketName:
    Value: !Ref UploadBucket
  TableName:
    Value: !Ref CatalogTable
  ApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
